# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Headers for PWA support
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
